### ISSUE TITLE
Logout on root directory

### ISSUE THREAD

**Issue by alietta** [AndreyTichinsky/react_project#18]
Если залогинится и перейти на корневую директорию, то нужно снова вводить имя пользователя, как будто произошел разлогин, но это не так. Если я сохраню адрес с именем пользователя к игре я все таки смогу вернуться.

**Comment by AndreyTichinsky** [comment]
Исправил, пока таким поведением - при выходе на корневую директорию в поле инпута будет введено залогиненое имя пользователя, так пользователь сможет вернуться в игру под тем же именем.
